image: ubuntu:16.04

stages:
  - pre-build
  - build
  - deploy
  - test

.linux_set_path: &linux_set_path_def
  before_script:
    - export PATH=$(pwd)/bin${PATH:+:$PATH}
  tags:
    - linux

.windows_set_path: &win_set_path_def
  before_script:
    - set PATH=%CD%\bin;%PATH%
  tags:
    - windows


build-windows:
  stage: build
  script:
    - ci\build.bat
  artifacts:
    paths:
      - bin\nim.exe
      - bin\nimd.exe
      - compiler\nim.exe
      - koch.exe
    expire_in: 1 week
  tags:
    - windows

deploy-windows:
  stage: deploy
  script:
    - koch.exe winrelease
  artifacts:
    paths:
      - build/*.exe
      - build/*.zip
    expire_in: 1 week
  tags:
    - windows
    - fast



test-windows:
  stage: test
  <<: *win_set_path_def
  script:
    - call ci\deps.bat
    - nim c testament\tester
    - testament\tester.exe all
  tags:
    - windows
    - fast
