sudo: false
language: c
os:
  - linux
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
before_script:
  - set -e
  - wget http://nim-lang.org/download/fasm-1.71.39.tgz
  - tar xvf fasm-1.71.39.tgz
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - sed -i -e 's,cc = gcc,cc = clang,' config/nim.cfg
  - export PATH=$(pwd)/bin:$(pwd)/fasm:$PATH
script:
  - nim c koch
  - ./koch boot
  - ./koch boot -d:release
  - nim e install_nimble.nims
  - nim e tests/test_nimscript.nims
  - nimble update
  - nimble install zip
  - nimble install opengl
  - nimble install sdl1
  - nimble install jester@#head
  - nimble install niminst
  - nim c --taintMode:on tests/testament/tester
  - tests/testament/tester --pedantic all
  - ./koch csource
  - ./koch xz
