sudo: false
language: c
os:
  - linux
  - osx
dist: trusty

matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
  brew:
    packages:
    - boehmgc
    - node

before_script:
  - set -e
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - sed -i -e 's,cc = gcc,cc = clang,' config/nim.cfg
  - export PATH=$(pwd)/bin:$PATH
script:
  - nim c koch
  - ./koch boot
  - ./koch boot -d:release
  - ./koch nimble
  - nim e tests/test_nimscript.nims
  - nimble install zip -y
  - nimble install opengl
  - nimble install sdl1
  - nimble install jester@#head
  - nimble install niminst
  - nim c --taintMode:on -d:nimCoroutines tests/testament/tester
  - tests/testament/tester --pedantic all -d:nimCoroutines
  - ./koch csource
  - ./koch xz
