sudo: false
language: c

dist: xenial

matrix:
  fast_finish: true

  include:
    - os: linux
      env: NIM_COMPILE_TO_CPP=false

    - os: osx
      env: NIM_COMPILE_TO_CPP=false

    - os: osx
      env: NIM_COMPILE_TO_CPP=true

# To allow failures for a failing configuration, use something like:
#  allow_failures:
#    - env: NIM_COMPILE_TO_CPP=true
#    - os: osx

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev
  homebrew:
    packages:
    - boehmgc
    - make
    - sfml

before_script:
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - make -C csources -j 2 LD=$CC
  - export PATH=$(pwd)/bin${PATH:+:$PATH}

script:
  - echo "travis_fold:start:nim_c_koch"
  - nim c koch
  - echo "travis_fold:end:nim_c_koch"
  - ./koch runCI

before_deploy:
  # Make https://nim-lang.github.io/Nim work the same as https://nim-lang.github.io/Nim/overview.html
  - cp -f ./doc/html/overview.html ./doc/html/index.html
deploy:                         # https://nim-lang.github.io/Nim
  provider: pages
  # local-dir *has* to be a relative path from the repo root.
  local-dir: "doc/html"
  skip-cleanup: true
  github-token: "$GITHUB_OAUTH_TOKEN"
  keep-history: false
  on:
    branch: devel

# Extract failed tests
after_failure: nim c -r tools/ci_testresults.nim
