sudo: false
language: c

dist: xenial

matrix:
  include:
    - os: linux
      env:
        - NIM_COMPILE_TO_CPP=false
        - CPU=amd64

addons:
  apt:
    # update the list above if more deps are introduced
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev
    - libc6-dbg
    - valgrind

before_script:
  - git clone --depth 1 https://github.com/nim-lang/csources_v1.git csources
  - export PATH="$PWD/bin${PATH:+:$PATH}"
  - make -C csources -j 2 LD=$CC ucpu=$CPU

script:
  - echo "travis_fold:start:nim_c_koch"
  - nim c koch
  - echo "travis_fold:end:nim_c_koch"
  - echo "travis_fold:start:koch_boot"
  - ./koch boot
  - echo "travis_fold:end:koch_boot"
  - echo "travis_fold:start:koch_doc"
  - ./koch doc
  - echo "travis_fold:end:koch_doc"

before_deploy:
  # Make https://nim-lang.github.io/Nim work the same as https://nim-lang.github.io/Nim/overview.html
  - cp -f ./doc/html/overview.html ./doc/html/index.html

deploy:                         # https://nim-lang.github.io/Nim
  provider: pages
  # local-dir *has* to be a relative path from the repo root.
  local-dir: "doc/html"
  skip-cleanup: true
  github-token: "$GITHUB_OAUTH_TOKEN"
  keep-history: false
  on:
    branch: devel
