sudo: false
language: c
os:
  - linux
  - osx
dist: trusty


matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boehmgc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sfml; fi

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - export PATH=$(pwd)/bin${PATH:+:$PATH}
script:
  - nim c koch
  - ./koch boot
  - ./koch boot -d:release
  - ./koch nimble
  - nim e tests/test_nimscript.nims
  - nimble install zip -y
  - nimble install opengl
  - nimble install sdl1
  - nimble install jester@#head
  - nimble install niminst
  - nim c --taintMode:on -d:nimCoroutines tests/testament/tester
  - tests/testament/tester --pedantic all -d:nimCoroutines
  - ./koch web
  - ./koch csource
  - ./koch nimsuggest
#  - nim c -r nimsuggest/tester
  - ( ! grep -F '.. code-block' -l -r --include '*.html' --exclude contributing.html --exclude docgen.html --exclude tut2.html )
  - ( ! grep -F '..code-block' -l -r --include '*.html' --exclude contributing.html --exclude docgen.html --exclude tut2.html )
