version: '{build}'

environment:
  DLLS_URL: https://nim-lang.org/download/dlls.zip
  DLLS_ARCHIVE: dlls.zip
  MINGW_DIR: mingw64
  MINGW_URL: https://nim-lang.org/download/mingw64.7z
  MINGW_ARCHIVE: mingw64.7z

  matrix:
    - NIM_TEST_PACKAGES: false
    - NIM_TEST_PACKAGES: true

cache:
    - '%MINGW_ARCHIVE%'
    - '%DLLS_ARCHIVE%'


install:
  - ps: Install-Product node 8 # node 8 or later is required to test js async stuff
  - IF not exist "%DLLS_ARCHIVE%" appveyor DownloadFile "%DLLS_URL%" -FileName "%DLLS_ARCHIVE%"
  - 7z x -y "%DLLS_ARCHIVE%" -o"%CD%\BIN"> nul
  - IF not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" -o"%CD%\DIST"> nul
  - SET PATH=%CD%\DIST\%MINGW_DIR%\BIN;%CD%\BIN;%PATH%
  - git clone --depth 1 https://github.com/nim-lang/csources
  - cd csources
  - build64.bat
  - cd ..

build_script:
  - openssl version
  - openssl version -d
  - bin\nim c koch
  - koch runCI

deploy: off
