strategy:
  matrix:
    Linux_amd64:
      pool:
        vmImage: 'ubuntu-16.04'
      CPU=amd64
      NIM_COMPILE_TO_CPP=false
    Linux_i386:
      pool:
        vmImage: 'ubuntu-16.04'
      CPU=i386
      NIM_COMPILE_TO_CPP=false
    OSX_amd64:
      pool:
        vmImage: 'macOS-10.14'
      CPU=amd64
      NIM_COMPILE_TO_CPP=false
    OSX_amd64_cpp:
      pool:
        vmImage: 'macOS-10.14'
      CPU=amd64
      NIM_COMPILE_TO_CPP=true

steps:
  - script: |
      sudo apt-get update -qq
      DEBIAN_FRONTEND='noninteractive' \
        sudo apt-get install --no-install-recommended -yq \
          libcurl4-openssl-dev libgc-dev libsdl1.2-dev libsfml-dev
    displayName: 'Install dependencies (amd64 Linux)'
    condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['CPU'], 'amd64'))

  - script: |
      sudo apt-get update -qq
      DEBIAN_FRONTEND='noninteractive' \
        sudo apt-get install --no-install-recommended -yq \
        g++-multilib gcc-multilib libcurl4-openssl-dev:i386 libgc-dev:i386 \
        libsdl1.2-dev:i386 libsfml-dev:i386
    displayName: 'Install dependencies (i386 Linux)'
    condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['CPU'], 'i386'))

  - script: brew install boehmgc make sfml
    displayName: 'Install dependencies (OSX)'
    condition: eq(variables['Agent.OS'], 'Darwin')
